algoritmo "semnome"
// Função : Verificar entre dois números qual é maior 
// Autor :
// Data : 29/09/2025
// Seção de Declarações
var
  num1, num2: inteiro
inicio
  escreva("Digite o primeiro número: ")
  leia(num1)
  escreva("Digite o segundo número: ")
  leia(num2)

  se num1 > num2 entao
    escreva(num1, " é maior que ", num2)
  senao
    escreva(num2, " é maior que ", num1)
      fimse
      
fimalgoritmo

